### ISSUE TITLE
Level1 - Issue of Node.js & Express.js API

### ISSUE THREAD

**Issue by ksnx3684** [ksnx3684/hanghae_level1#1]

**Comment by ksnx3684** [comment]
https://github.com/ksnx3684/hanghae_level1/commit/ce940869c6c0d175ec9c8581d6f885926d0951af

URI에 한글이나 특수 문자가 포함 시 에러를 잡아내지 못하던 문제 수정

**Comment by ksnx3684** [comment]
https://github.com/ksnx3684/hanghae_level1/commit/03433f0f8089533ca86ca9023878ed325eeaea86

게시글 조회 오류 수정

**Comment by Yunjaejo** [comment]
병훈님 안녕하세요! 코드 잘 봤습니다. 몇가지 코멘트드립니다.
1. pk로 사용할 수 있는 _id 값을 _postId로 새로 맵핑하는 이유가 있을까요? 그리고 param에서 받아온 _id를 find 등의 mongoose 메소드에서 바로 사용하지 않고 new ObjectId 객체를 만들어서 조회하는 이유가 궁금합니다.

2. post router에서 댓글 API까지 작성되어있는데 comment router로 따로 분리한다면 관리하기 더 좋을 것 같아요.

3. validation check 할 때 24자 제한하고 있습니다. Magic Number / Magic Literal 에 대해서 적용해보세요!

4. 댓글삭제 API에서 중첩된 if문을 사용하고 있습니다. Guard Clause / Early Return 개념을 찾아보시면 좋을 것 같습니다.

5. 스키마에서 CreatedAt 필드를 Date.now() 로 사용하지 않고 항상 new Date를 만들어서 넣어주는 특별한 이유가 있나요? _id처럼 따로 넣어주지 않아도 도큐먼트가 만들어지는 시점에 DB단에서 생성시간을 넣어줄 수 있습니다.

레벨1 과제하시느라 너무 고생하셨습니다~!

**Comment by ksnx3684** [comment]
매니저님 안녕하세요 피드백 감사드립니다.

- 1번에서 말씀주신대로 댓글 기능 구현 시 _postId로 따로 맵핑한 이유는 입문주차 강의에서 goods와 cart 스키마에서 goodsId로 맵핑하여 서로 연결했다는 점에 착안하여 비슷한 방식으로 적용하였습니다.
comments 스키마에 _postId를 추가한 다음 댓글 생성시 URI의 postId 값을 req.params로 불러와 같이 DB에 삽입한 뒤, 댓글 조회 시 해당 게시글의 postId 값을 갖고 있는 댓글 만을 조회하여 찾는다는 개념으로 구현하였습니다.
또한 RDBMS와 다르게 NoSQL 환경에서 아직 PK를 사용해 본 경험이 없었고, 위와 같은 방식으로 구현하는 것이 더 빠르게 구현할 수 있다고 생각하였습니다.

- new ObjectId의 경우에는 처음에 await Posts.findOne({_id: _postId}); 형식으로 사용했었으나 값을 찾지 못하는 오류가 발생하여 형 변환이 필요하다는 생각에 await Posts.findOne({_id: ObjectId(_postId)}); 로 시도해봤습니다.
그러나 TypeError: Class constructor ObjectId cannot be invoked without 'new' 에러가 발생하였고 다시 new를 선언하였더니 BSON 에러가 발생하는 등 지속적인 오류가 발생하였으며, 이후 여러 방법으로 시도하던 중 현재와 같은 상태에서 정상 동작하여 지금에 이르렀습니다.
정확한 원인은 모르겠으나 매니저님께서 말씀주신 대로 다시 findOne({_id: _postId})로 수정 후 기동해보니 정상 동작하는 것을 확인하였습니다. 여러가지를 추측해 보건데, 처음 req.params로 불러오는 과정에서 구조 분해 할당법을 잘못 사용하였거나 에러처리를 잘못 하여 발생한 것이 아닌가로 생각됩니다.

나머지 사항들에 대해서도 조언 주신대로 다음 과제 제출 시 참고하여 진행하도록 하겠습니다.
감사합니다.
